### ISSUE TITLE
Add Fade effect in this shadow Drawer shader script

### ISSUE THREAD

**Issue by spacelydiagonal** [keijiro/ShadowDrawer#4]
Hello, Mr Takahashi, I really appreciate your great work with this transparency Matte shader script in Unity.
It is better than Kudan's default matte shader script.
Well, I have a  good idea which will make this script more attractive.
Shall we add fade effects for this script, I mean the shadow will be faded ( decrease the alpha transparency and blur on the edge ) based on the distance of the object so it looks like in real world, I really want to do but as I am a newbie in shader scripting, have lots of issues while developing.
I kindly hope you let me know how to enhance your majestic matte transparent shadow with fading effects.
Best regards and hope your great response.
PS, have a good weekend on your side. :)

**Comment by spacelydiagonal** [comment]
Well, I mean the shadow with fading based on the distance between object and shadow point, the far the shadow point the transparent the shadow color is.
also if there is a soft edge for shadow then it is great.
Do you think it is difficult to implement?

**Comment by spacelydiagonal** [comment]
Oh, I will add the images with the shadow I want to look for in unity with transparent shadow catcher plane.
![images](https://user-images.githubusercontent.com/20052126/27507056-66387412-5902-11e7-9a95-1dea863d8713.jpg)
![images 1](https://user-images.githubusercontent.com/20052126/27507062-755fee2a-5902-11e7-91a3-3c8380762236.jpg)
![images 2](https://user-images.githubusercontent.com/20052126/27507063-7f7d8778-5902-11e7-80f3-de17f6fcf672.jpg)

**Comment by spacelydiagonal** [comment]
Is it possible?

**Comment by spacelydiagonal** [comment]
I hope to integrate this shadow with Gaussian blurring.
Will you please let me know how to do it?
Thanks

**Comment by keijiro** [comment]
The original purpose of ShadowDrawer is just drawing shadows on transparent backgrounds. What you're suggesting is not supported with the standard feature set of Unity.  It needs extending the standard renderer/shader of Unity, and it's not in the scope of this repository.

I'm closing this ticket. Please feel free to reopen for further discussions.
