### ISSUE TITLE
Shader doesn't compile in 2018.1

### ISSUE THREAD

**Issue by nolwenn-bigoin** [keijiro/ShadowDrawer#6]
Hello,
This shader no longer compiles in Unity 2018.1.0b13. I believe this has something to do with the LIGHT_ATTENUATION macro being deprecated. Could you have a look ?
Thanks.

**Comment by nolwenn-bigoin** [comment]
I replaced 
half atten = LIGHT_ATTENUATION(IN);
with
UNITY_LIGHT_ATTENUATION(atten, IN, IN.pos.xyz);
Is this correct ?
I can't see shadows from spotlight, only directional. Is this normal behaviour ?

**Comment by keijiro** [comment]
I pushed the correction to the `unity2018` branch.

https://github.com/keijiro/ShadowDrawer/commit/d7c0d08ecf42b8d7822d4e09f3ffaa46cf3daff9

> I can't see shadows from spotlight, only directional. Is this normal behaviour ?

Yes. It only works properly with the directional light.

**Comment by keijiro** [comment]
I'm closing the issue. Please feel free to reopen for further questions.
