### ISSUE TITLE
Broken in Unity 2018.1

### ISSUE THREAD

**Issue by eAi** [keijiro/ShadowDrawer#8]
This appears to have broken in Unity 2018.1 (.5) due to the LIGHT_ATTENUATION macro being removed and replaced.

This thread explains the change: https://forum.unity.com/threads/missing-changed-light_attenuation-macro.511767/

**Comment by keijiro** [comment]
This is a known issue that I've already fixed in a branch. Please see #6

**Comment by eAi** [comment]
Thanks, didn’t see the closed issue, or the branch!
