### ISSUE TITLE
ShadowDrawer.shader compile error in Unity 2018

### ISSUE THREAD

**Issue by AmadeusSVX** [keijiro/ShadowDrawer#9]
In Unity 2018.1.6f1 (probably same in other 2018 versions), 
LIGHT_ATTENUATION macro is not supported anymore.
So ShadowDrawer compile will be failed.

**Comment by keijiro** [comment]
This is a known issue that I've already fixed in a branch. Please see #6

**Comment by mmspacediagonal** [comment]
Is your shader is okay for mobile android and ios?
